/*
 * Copyright 2015-2026 Ritense BV, the Netherlands.
 *
 * Licensed under EUPL, Version 1.2 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {buildCustomComponentEditForm} from '@valtimo/components';

const documentenApiUploaderDisplayComponents = [
  {
    type: 'textfield',
    input: true,
    key: 'label',
    label: 'Label',
    placeholder: 'Label',
    weight: 0,
    validate: {
      required: true,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'validate.required',
    label: 'Required',
    weight: 10,
    validate: {
      required: false,
    },
  },
  {
    type: 'textfield',
    input: true,
    key: 'key',
    label: 'Property Name',
    placeholder: 'Property Name',
    tooltip: 'The name of this field in the API endpoint.',
    weight: 20,
    validate: {
      required: true,
    },
  },
  {
    type: 'textfield',
    input: true,
    key: 'customOptions.title',
    label: 'Title',
    placeholder: 'Title',
    tooltip: 'Leave empty to use the default title',
    weight: 30,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.hideTitle',
    label: 'Hide title',
    weight: 40,
    validate: {
      required: false,
    },
  },
  {
    type: 'textfield',
    input: true,
    key: 'customOptions.subtitle',
    label: 'Subtitle',
    placeholder: 'Title',
    tooltip: 'Leave empty to hide subtitle',
    weight: 50,
    validate: {
      required: false,
    },
  },
  {
    type: 'number',
    input: true,
    key: 'customOptions.maxFileSize',
    label: 'Maximum file size',
    placeholder: 'Maximum file size',
    defaultValue: 5,
    weight: 60,
    validate: {
      required: true,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.hideMaxFileSize',
    label: 'Hide maximum file size',
    weight: 70,
    validate: {
      required: false,
    },
  },
  {
    type: 'number',
    input: true,
    key: 'customOptions.maxFiles',
    label: 'Maximum number of files',
    placeholder: 'Maximum number of files',
    tooltip: 'The maximum number of files that may be uploaded. Leave empty for no limit.',
    weight: 80,
    validate: {
      required: false,
      min: 1,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.camera',
    label: 'Allow camera uploads',
    weight: 90,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'disabled',
    label: 'Disabled',
    tooltip: 'Disable the upload field',
    weight: 100,
    validate: {
      required: false,
    },
  },
  {
    type: 'textfield',
    input: true,
    key: 'customOptions.acceptedFiles',
    label: 'Accepted file types (leave blank for no restrictions)',
    placeholder: '.png, .docx, .pdf',
    defaultValue: '',
    weight: 110,
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.hideAcceptedFiles',
    label: 'Hide accepted file types',
    weight: 120,
    validate: {
      required: false,
    },
  },
  {
    label: 'HTML',
    tag: 'div',
    content: '<h3>Process variables</h3>',
    refreshOnChange: false,
    type: 'htmlelement',
    input: false,
    tableView: false,
    weight: 130,
  },
  {
    type: 'textfield',
    input: true,
    key: 'customOptions.documentUrlProcessVariable',
    label: 'Document URL',
    tooltip:
      "Specify the process variable name where the Documenten API document URL will be stored. Defaults to 'documentUrl' if left empty.",
    weight: 140,
    validate: {
      required: false,
    },
  },
  {
    label: 'HTML',
    tag: 'div',
    content: '<h3>Documenten API metadata</h3>',
    refreshOnChange: false,
    type: 'htmlelement',
    input: false,
    tableView: false,
    weight: 150,
  },
  {
    label: 'HTML',
    tag: 'div',
    content: '<h4>Filename</h4>',
    refreshOnChange: false,
    type: 'htmlelement',
    input: false,
    tableView: false,
    weight: 160,
  },
  {
    type: 'textfield',
    input: true,
    key: 'customOptions.filename',
    label: 'Default filename',
    tooltip: 'Leave empty to let the user input their own filename',
    weight: 170,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.disableFilename',
    label: 'Disable filename input',
    weight: 180,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.hideFilename',
    label: 'Hide filename input',
    weight: 190,
    validate: {
      required: false,
    },
  },
  {
    label: 'HTML',
    tag: 'div',
    content: '<h4>Title</h4>',
    refreshOnChange: false,
    type: 'htmlelement',
    input: false,
    tableView: false,
    weight: 200,
  },
  {
    type: 'textfield',
    input: true,
    key: 'customOptions.documentTitle',
    label: 'Default document title',
    tooltip: 'Leave empty to let the user input their own title',
    weight: 210,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.disableDocumentTitle',
    label: 'Disable document title input',
    weight: 220,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.hideDocumentTitle',
    label: 'Hide document title input',
    weight: 230,
    validate: {
      required: false,
    },
  },
  {
    label: 'HTML',
    tag: 'div',
    content: '<h4>Author</h4>',
    refreshOnChange: false,
    type: 'htmlelement',
    input: false,
    tableView: false,
    weight: 240,
  },
  {
    type: 'textfield',
    input: true,
    key: 'customOptions.author',
    label: 'Default author',
    tooltip: 'Leave empty to let the user input their own author',
    weight: 250,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.disableAuthor',
    label: 'Disable author input',
    weight: 260,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.hideAuthor',
    label: 'Hide author input',
    weight: 270,
    validate: {
      required: false,
    },
  },
  {
    label: 'HTML',
    tag: 'div',
    content: '<h4>Description</h4>',
    refreshOnChange: false,
    type: 'htmlelement',
    input: false,
    tableView: false,
    weight: 280,
  },
  {
    type: 'textfield',
    input: true,
    key: 'customOptions.description',
    label: 'Default description',
    tooltip: 'Leave empty to let the user input their own description',
    weight: 290,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.disableDescription',
    label: 'Disable description input',
    weight: 300,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.hideDescription',
    label: 'Hide description input',
    weight: 310,
    validate: {
      required: false,
    },
  },
  {
    label: 'HTML',
    tag: 'div',
    content: '<h4>Language</h4>',
    refreshOnChange: false,
    type: 'htmlelement',
    input: false,
    tableView: false,
    weight: 320,
  },
  {
    type: 'select',
    label: 'Default language',
    key: 'customOptions.language',
    placeholder: 'Select a default language',
    data: {
      values: [
        {value: 'nld', label: 'Dutch'},
        {value: 'eng', label: 'English'},
        {value: 'deu', label: 'German'},
      ],
    },
    dataSrc: 'values',
    input: true,
    weight: 330,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.disableLanguage',
    label: 'Disable language input',
    weight: 340,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.hideLanguage',
    label: 'Hide language input',
    weight: 350,
    validate: {
      required: false,
    },
  },
  {
    label: 'HTML',
    tag: 'div',
    content: '<h4>Confidentiality level</h4>',
    refreshOnChange: false,
    type: 'htmlelement',
    input: false,
    tableView: false,
    weight: 360,
  },
  {
    type: 'select',
    label: 'Default confidentiality level',
    key: 'customOptions.confidentialityLevel',
    placeholder: 'Select a default confidentiality level',
    data: {
      values: [
        {value: 'openbaar', label: 'Public'},
        {value: 'beperkt_openbaar', label: 'Restricted public'},
        {value: 'intern', label: 'Internal'},
        {value: 'zaakvertrouwelijk', label: 'Case confidential'},
        {value: 'vertrouwelijk', label: 'Private'},
        {value: 'confidentieel', label: 'Confidential'},
        {value: 'geheim', label: 'Secret'},
        {value: 'zeer_geheim', label: 'Very secret'},
      ],
    },
    dataSrc: 'values',
    input: true,
    weight: 370,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.disableConfidentialityLevel',
    label: 'Disable confidentiality level input',
    weight: 380,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.hideConfidentialityLevel',
    label: 'Hide confidentiality level input',
    weight: 390,
    validate: {
      required: false,
    },
  },
  {
    label: 'HTML',
    tag: 'div',
    content: '<h4>Creation date</h4>',
    refreshOnChange: false,
    type: 'htmlelement',
    input: false,
    tableView: false,
    weight: 400,
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.disableCreationDate',
    label: 'Disable creation date input',
    weight: 410,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.hideCreationDate',
    label: 'Hide creation date input',
    weight: 420,
    validate: {
      required: false,
    },
  },
  {
    label: 'HTML',
    tag: 'div',
    content: '<h4>Informatieobjecttype</h4>',
    refreshOnChange: false,
    type: 'htmlelement',
    input: false,
    tableView: false,
    weight: 430,
  },
  {
    type: 'textfield',
    input: true,
    key: 'customOptions.documentType',
    label: 'Default informatieobjecttype url',
    tooltip:
      "Sometimes referred to as the 'document-type'. Must match the informatieobjecttype url exactly. Leave empty to let the user input their own informatieobjecttype",
    weight: 440,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.disableDocumentType',
    label: 'Disable informatieobjecttype input',
    weight: 450,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.hideDocumentType',
    label: 'Hide informatieobjecttype input',
    weight: 460,
    validate: {
      required: false,
    },
  },
  {
    label: 'HTML',
    tag: 'div',
    content: '<h4>Status</h4>',
    refreshOnChange: false,
    type: 'htmlelement',
    input: false,
    tableView: false,
    weight: 470,
  },
  {
    type: 'select',
    label: 'Default status',
    key: 'customOptions.status',
    placeholder: 'Select a default status',
    data: {
      values: [
        {value: 'in_bewerking', label: 'In editing'},
        {value: 'ter_vaststelling', label: 'To be confirmed'},
        {value: 'definitief', label: 'Definitive'},
        {value: 'gearchiveerd', label: 'Archived'},
      ],
    },
    dataSrc: 'values',
    input: true,
    weight: 480,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.disableStatus',
    label: 'Disable status input',
    weight: 490,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.hideStatus',
    label: 'Hide status input',
    weight: 500,
    validate: {
      required: false,
    },
  },
  {
    label: 'HTML',
    tag: 'div',
    content: '<h4>Additional date</h4>',
    refreshOnChange: false,
    type: 'htmlelement',
    input: false,
    tableView: false,
    weight: 510,
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.hideAdditionalDate',
    label: 'Hide additional date input',
    weight: 520,
    validate: {
      required: false,
    },
  },
  {
    label: 'HTML',
    tag: 'div',
    content: '<h4>Tags</h4>',
    refreshOnChange: false,
    type: 'htmlelement',
    input: false,
    tableView: false,
    weight: 530,
  },
  {
    type: 'textfield',
    input: true,
    key: 'customOptions.tags',
    label: 'Default tags',
    tooltip: 'A comma separated list of tags. Leave empty to let the user input their own tags',
    weight: 540,
    validate: {
      required: false,
    },
  },
  {
    type: 'checkbox',
    input: true,
    inputType: 'checkbox',
    key: 'customOptions.hideTags',
    label: 'Hide tags input',
    weight: 550,
    validate: {
      required: false,
    },
  },
];

export const documentenApiUploaderEditForm = () =>
  buildCustomComponentEditForm(documentenApiUploaderDisplayComponents);
