name: gzac-docker-compose

services:
  openzaak:
    networks:
      - default
      - wopi-network

  gotenberg:
    networks:
      - default
      - wopi-network

networks:
  wopi-network:
    external: true
