name: valtimo-docker-compose

services:
    # Valtimo core

    valtimo-keycloak:
        container_name: valtimo-docker-compose-valtimo-keycloak
        depends_on:
            - valtimo-keycloak-database
        image: quay.io/keycloak/keycloak:26.6
        ports:
            - "8081:8080"
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://valtimo-keycloak-database/keycloak
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: keycloak
            KC_FEATURES: token-exchange,admin-fine-grained-authz
            KC_HTTP_RELATIVE_PATH: /auth
            KC_HOSTNAME_STRICT: false
            KC_HOSTNAME_STRICT_HTTPS: false
        volumes:
            - ./imports/keycloak:/opt/keycloak/data/import
        command:
            - start-dev
            - --import-realm
            - --http-enabled=true
            - --hostname-strict=false
        healthcheck:
            test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() == 200 ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/auth' ]
            interval: 10s
            timeout: 5s
            retries: 60
            start_period: 5s

    valtimo-keycloak-database:
        image: postgres:17.4
        container_name: valtimo-docker-compose-valtimo-keycloak-database
        ports:
            - "54329:5432"
        environment:
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: keycloak

    valtimo-database:
        container_name: valtimo-docker-compose-valtimo-database
        image: postgres:17.4
        ports:
            - "54320:5432"
        environment:
            POSTGRES_USER: valtimo
            POSTGRES_PASSWORD: password
            POSTGRES_DB: valtimo
        volumes:
            - valtimo-database-data:/var/lib/postgres # persist data even if container shuts down

    valtimo-database-mysql:
        container_name: valtimo-docker-compose-valtimo-database-mysql
        image: mysql/mysql-server:8.0.28-1.2.7-server
        profiles:
            - mysql
        ports:
            - "33060:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: valtimo
            MYSQL_USER: valtimo
            MYSQL_PASSWORD: password
            MYSQL_ROOT_HOST: "%"
        command:
            --default-authentication-plugin=mysql_native_password
            --lower_case_table_names=1
            --collation-server=utf8mb4_unicode_ci
            --character-set-server=utf8mb4
            --explicit_defaults_for_timestamp
            --ssl=false
            --innodb_flush_method=O_DIRECT
            --sql_mode=NO_ENGINE_SUBSTITUTION
            --transaction-isolation=READ-COMMITTED
        volumes:
            - valtimo-database-data-mysql:/var/lib/mysql # persist data even if container shuts down

    valtimo-rabbitmq:
        image: rabbitmq:4.1.0-management
        container_name: valtimo-docker-compose-valtimo-rabbitmq
        volumes:
            - ./imports/valtimo-rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
            - ./imports/valtimo-rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq.conf
        command: >
            bash -c "
              rabbitmq-plugins enable --offline rabbitmq_stream rabbitmq_stream_management &&
              rabbitmq-server
            "

    # LocalStack (AWS services emulation)
    localstack:
        image: localstack/localstack:3.7
        container_name: valtimo-docker-compose-localstack
        ports:
            - "4566:4566"
        environment:
            SERVICES: s3
            AWS_DEFAULT_REGION: eu-west-1
        volumes:
            - "./imports/localstack:/etc/localstack/init/ready.d"

    # Gotenberg (PDF conversion API)
    gotenberg:
        image: gotenberg/gotenberg:8
        container_name: gotenberg-pdf-conversion-api
        ports:
            - "3000:3000"
        environment:
            API_TIMEOUT: "240s"

volumes:
    valtimo-database-data:
    valtimo-database-data-mysql:
