export {
  BUILDING_BLOCK_MANAGEMENT_LIST_TEST_IDS,
  BUILDING_BLOCK_MANAGEMENT_CREATE_TEST_IDS,
  BUILDING_BLOCK_MANAGEMENT_UPLOAD_TEST_IDS,
  BUILDING_BLOCK_MANAGEMENT_DETAIL_TEST_IDS,
  BUILDING_BLOCK_MANAGEMENT_METADATA_TEST_IDS,
  BUILDING_BLOCK_MANAGEMENT_ARTWORK_TEST_IDS,
  BUILDING_BLOCK_MANAGEMENT_PLUGINS_TEST_IDS,
  BUILDING_BLOCK_MANAGEMENT_DETAIL_ACTIONS_TEST_IDS,
  BUILDING_BLOCK_VERSION_OPTION_TEST_ID_PREFIX,
} from '../../frontend/projects/valtimo/building-block-management/src/lib/constants/building-block-management.test-ids';
