export {
  BB_MAPPINGS_TEST_IDS,
  PLUGIN_ACTION_CONFIGURATION_TEST_IDS,
  PROCESS_LINK_MODAL_TEST_IDS,
  PROCESS_LINK_TYPE_BUTTON_TEST_ID_PREFIX,
  PROCESS_LINK_TYPE_CHOOSER_TEST_IDS,
  SELECT_PLUGIN_ACTION_TEST_IDS,
  SELECT_PLUGIN_ACTION_TILE_TEST_ID_PREFIX,
  SELECT_PLUGIN_CONFIGURATION_ROW_TEST_ID_PREFIX,
  SELECT_PLUGIN_CONFIGURATION_TEST_IDS,
} from '../../frontend/projects/valtimo/process-link/src/lib/constants/process-link.test-ids';
