// utils/dataGenerator.ts
import { smartStep } from './smartStep';
import {caseManagementApi} from '../tests/domainGroups/caseManagement/api';

type EntityType = 'case' | 'form' | 'dashboard' | 'formFlow' | 'caseDefinition';

/**
 * Generates a short, unique ID based on timestamp and random characters.
 * Example: 'lmno23-f4x9'
 */
export function generateId(): string {
  return Date.now().toString(36) + '-' + Math.random().toString(36).substring(2, 6);
}

/**
 * Generates a standardized, readable name for any entity.
 * Example: 'case-lmno23-f4x9'
 */
export function generateName(entity: EntityType, prefix = ''): string {
  const base = prefix || entity;
  return `${base}-${generateId()}`;
}

/**
 * Provides domain-aware test data generators.
 * Only generate what you need.
 */
export const testData = {
  case: (overrides: Partial<{ name: string; description: string }> = {}) => ({
    name: overrides.name ?? generateName('case'),
    description: overrides.description ?? 'Autogenerated case for testing',
  }),

  caseDefinition: {
    build: (overrides: Partial<{ name: string; description: string }> = {}) => ({
      name: overrides.name ?? generateName('caseDefinition'),
      description: overrides.description ?? 'Autogenerated case definition for testing',
    }),

    setupWithCleanup: async (
      casePage: any,
      name: string,
      options?: { useApi?: boolean }
    ): Promise<() => Promise<void>> => {
      if (options?.useApi) {
        await smartStep('case definition', 'setup', 'API', async () => {
          console.log('create via api')
          await caseManagementApi.create(name);
        });
      } else {
        await smartStep('case definition', 'setup', 'UI', async () => {
          await casePage.goto();
          await casePage.createCaseDefinition(name);
        });
      }

      return async () => {
        await smartStep('case definition', 'cleanup', 'API', async () => {
            console.log('cant delete case defs');
          // await casePage.deleteViaApi(name).catch(() => {});
        });
      };
    },
  },

  form: {
    build: (overrides: Partial<{ name: string; key: string; fields: any[] }> = {}) => ({
      name: overrides.name ?? generateName('form'),
      key: overrides.key ?? generateId(),
      fields: overrides.fields ?? [{ label: 'Naam', type: 'textfield' }],
    }),
  },

  dashboard: (overrides: Partial<{ title: string; widgets: any[] }> = {}) => ({
    title: overrides.title ?? generateName('dashboard'),
    widgets: overrides.widgets ?? [],
  }),

  formFlow: {
    build: (overrides: Partial<{ name: string; steps: any[] }> = {}) => ({
      name: overrides.name ?? generateName('formFlow'),
      steps: overrides.steps ?? [],
    }),

    setupWithCleanup: async (
      formFlowPage: any,
      name: string,
      options?: { expectFailure?: boolean }
    ): Promise<() => Promise<void>> => {
      await smartStep('form flow', 'setup', 'UI', async () => {
        await formFlowPage.goto();
        await formFlowPage.createFormFlow(name, options);
      });

      return async () => {
        await smartStep('form flow', 'cleanup', 'API', async () => {
          await formFlowPage.deleteViaApi(name).catch(() => {});
        });
      };
    }
  },
};
