services:
    db:
        ports:
            - "3364:5432"
        environment:
            - POSTGRES_DB=case-mongodb-test
    mongodb:
        image: mongo:8.2.6
        ports:
            - "37017:27017"
