name: Backend - Build libraries and run tests

permissions:
  contents: read

on:
  workflow_call:
    outputs:
      build_artifact_name:
        description: Build artifact this workflow produces that can be retrieved with the 'download-artifact' action
        value: backend-build-output

  workflow_dispatch:

defaults:
  run:
    working-directory: backend

jobs:
  check_cache:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.restore_cache.outputs.cache-hit }}
      cache-key: backend-libraries-contents-${{ steps.compute_contents_hash.outputs.contents_hash }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compute backend contents hash
        id: compute_contents_hash
        run: |
          echo "contents_hash=$(git rev-parse HEAD:backend)" >> $GITHUB_OUTPUT
      - name: Restore backend libraries from build cache
        id: restore_cache
        uses: actions/cache/restore@v4
        with:
          path: |
            backend/.gradle
            backend/**/build
          key: backend-libraries-contents-${{ steps.compute_contents_hash.outputs.contents_hash }}
      # Even in case of a cache hit, artifact must be pulled from cache and uploaded to
      # the artifact registry to be available to subsequent jobs
      - name: Upload built libraries
        uses: actions/upload-artifact@v4
        with:
          name: backend-build-output
          retention-days: 1
          path: |
            backend/.gradle
            backend/**/build

  build_libraries:
    if: ${{ needs.check_cache.outputs.cache-hit != 'true' }}
    needs:
      - check_cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compute backend contents hash
        run: |
          echo "contents_hash=$(git rev-parse HEAD:backend)" >> $GITHUB_ENV

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: gradle
      - name: Build libraries
        run: ./gradlew assemble

      - name: Cache built backend libraries
        uses: actions/cache/save@v4
        with:
          path: |
            backend/.gradle
            backend/**/build
          key: ${{ needs.check_cache.outputs.cache-key }}

      - name: Upload built libraries
        uses: actions/upload-artifact@v4
        with:
          name: backend-build-output
          retention-days: 1
          path: |
            backend/.gradle
            backend/**/build
  determine-tests:
    if: ${{ needs.check_cache.outputs.cache-hit != 'true' }}
    runs-on: ubuntu-latest
    needs:
      - check_cache
    outputs:
      unit_test_matrix: ${{ steps.set_test_matrices.outputs.unit_test_matrix }}
      integration_test_matrix: ${{ steps.set_test_matrices.outputs.integration_test_matrix }}
      security_test_matrix: ${{ steps.set_test_matrices.outputs.security_test_matrix }}
    env:
      UNIT_TESTS_MATRIX: "/tmp/unit_tests_matrix"
      INTEGRATION_TESTS_MATRIX: "/tmp/integration_tests_matrix"
      SECURITY_TESTS_MATRIX: "/tmp/security_tests_matrix"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: "Setup jq"
        uses: dcarbone/install-jq-action@v3

      # Computing the test matrices takes ~2 minutes in GHA, so cache them with a cache key based on all the Gradle files
      - name: Cache test definitions
        id: cache-test-definitions
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ env.UNIT_TESTS_MATRIX }}
            ${{ env.INTEGRATION_TESTS_MATRIX }}
            ${{ env.SECURITY_TESTS_MATRIX }}
          key: testdefinitions-${{ hashFiles('backend/**/build.gradle', 'backend/**/build.gradle.kts', 'backend/**/settings.gradle', 'backend/**/settings.gradle.kts', 'backend/**/gradle.properties') }}
      - name: Make test matrices
        id: make_test_matrices
        if: steps.cache-test-definitions.outputs.cache-hit != 'true'
        run: |
          UNIT_TESTS_FILE='/tmp/unit_tests'
          INTEGRATION_TESTS_FILE='/tmp/integration_tests'
          SECURITY_TESTS_FILE='/tmp/security_tests'
          DRY_RUN=$(./gradlew test securityTesting integrationTesting --dry-run)
          touch $UNIT_TESTS_FILE $INTEGRATION_TESTS_FILE $SECURITY_TESTS_FILE
          while IFS= read -r line; do
            if [[ $line =~ (:[^[:space:]]+:test)\  ]]; then
              echo "$line" | cut -d ' ' -f 1 >> $UNIT_TESTS_FILE
            elif [[ $line =~ (:[^[:space:]]+:integrationTesting)\  ]]; then
              echo "$line" | cut -d ' ' -f 1 >> $INTEGRATION_TESTS_FILE
            elif [[ $line =~ (:[^[:space:]]+:securityTesting)\  ]]; then
              echo "$line" | cut -d ' ' -f 1 >> $SECURITY_TESTS_FILE
            fi
          done <<< "$DRY_RUN"
          cat $UNIT_TESTS_FILE | jq -R -s -c 'split("\n")[:-1]' > $UNIT_TESTS_MATRIX
          cat $INTEGRATION_TESTS_FILE | jq -R -s -c 'split("\n")[:-1]' > $INTEGRATION_TESTS_MATRIX
          cat $SECURITY_TESTS_FILE | jq -R -s -c 'split("\n")[:-1]' > $SECURITY_TESTS_MATRIX
      - name: Set test matrices
        id: set_test_matrices
        run: |
          echo "unit_test_matrix=$(cat $UNIT_TESTS_MATRIX)" >> $GITHUB_OUTPUT
          echo "integration_test_matrix=$(cat $INTEGRATION_TESTS_MATRIX)" >> $GITHUB_OUTPUT
          echo "security_test_matrix=$(cat $SECURITY_TESTS_MATRIX)" >> $GITHUB_OUTPUT
  # Run the following test suites in parallel
  unit-testing:
    needs: [determine-tests, build_libraries, check_cache]
    if: ${{ needs.check_cache.outputs.cache-hit != 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unit_test_suite: ${{ fromJson(needs.determine-tests.outputs.unit_test_matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download built libraries
        uses: actions/download-artifact@v4
        with:
          name: backend-build-output
          path: .
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: gradle
      - name: Run Unit Tests
        run: ./gradlew ${{ matrix.unit_test_suite }}

  integration-testing:
    runs-on: ubuntu-latest
    needs: [determine-tests, build_libraries, check_cache]
    if: ${{ needs.check_cache.outputs.cache-hit != 'true' }}
    strategy:
      matrix:
        integration_test_suite: ${{ fromJson(needs.determine-tests.outputs.integration_test_matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download built libraries
        uses: actions/download-artifact@v4
        with:
          name: backend-build-output
          path: .
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: gradle
      - name: Run integration test suite
        run: ./gradlew ${{ matrix.integration_test_suite }}

  security-testing:
    needs: [determine-tests, build_libraries, check_cache]
    strategy:
      matrix:
        security_test_suite: ${{ fromJson(needs.determine-tests.outputs.security_test_matrix) }}
    if: |
      needs.check_cache.outputs.cache-hit != 'true' &&
      github.ref_type == 'branch' && 
      (
        startsWith(github.ref_name, 'development/') ||
        startsWith(github.ref_name, 'rc/') ||
        startsWith(github.ref_name, 'release/') ||
        github.ref_name == 'next-minor' ||
        github.ref_name == 'next-major' 
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download built libraries
        uses: actions/download-artifact@v4
        with:
          name: backend-build-output
          path: .
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: gradle
      - name: Run Security Tests
        run: ./gradlew ${{ matrix.security_test_suite }}
