name: "Run backend CI"
on:
  push:
    branches:
      - next-minor
    paths:
      - .github/workflows/backend_*.yml
      - backend/**
  pull_request:
    paths:
      - .github/workflows/backend_*.yml
      - backend/**

permissions:
  actions: write
  contents: read
  packages: write

jobs:
  build_and_test_libraries:
    name: Build and test libraries
    uses: ./.github/workflows/backend_build_test_libraries.yml
    secrets: inherit

  build_and_push_image:
    name: Build and push image
    needs: build_and_test_libraries
    uses: "./.github/workflows/backend_build_push_docker_image.yml"
    secrets: inherit
    with:
      backend_libraries_build_artifact_name: ${{ needs.build_and_test_libraries.outputs.build_artifact_name }}
      variant: dev

  # For pushes
  # publish_snapshot:
  # if ${{ github.event_name == 'push' }}
  # TODO, make separate workflow for publishing snapshots with JReleaser

  # For pull requests
  update_test_env:
    if: ${{ github.event_name == 'pull_request'}}
    needs:
      - build_and_push_image
      - build_and_test_libraries
    uses: ./.github/workflows/tag_test_env_image.yml
    secrets: inherit
    with:
      target: "gzac-backend"
      image_to_tag: ${{ needs.build_and_push_image.outputs.built_test_image }}
      contents_sha: ${{ needs.build_and_test_libraries.outputs.contents_sha }}
