name: "Run backend CI"
on:
  push:
    branches:
      - feature/create-test-env-on-pr
  pull_request:
    paths:
      - backend/**

  # For testing this workflow
  workflow_dispatch:
    inputs:
      envName:
        description: "Test environment name"
        required: true
        type: string

permissions:
  actions: write
  contents: read
  packages: write

jobs:
  build_and_test_libraries:
    name: Build and test libraries
    uses: ./.github/workflows/backend_build_test_libraries.yml
    secrets: inherit

  build_and_push_image:
    name: Build and push image
    needs: build_and_test_libraries
    uses: "./.github/workflows/backend_build_push_docker_image.yml"
    secrets: inherit
    with:
      backend_build_artifact_name: ${{ needs.build_and_test_libraries.outputs.build_artifact_name }}

  determine_test_env:
    uses: ./.github/workflows/determine_test_env.yml

  update_test_env:
    needs:
      - build_and_push_image
      - determine_test_env
    uses: ./.github/workflows/tag_test_env.yml
    secrets: inherit
    with:
      image: ghcr.io/${{ github.repository }}/gzac-backend
      image_tag: ${{ needs.build_and_push_image.outputs.image_tag }}
      source_sha: ${{ needs.determine_test_env.outputs.source_sha }}
      test_environment_name: ${{ needs.determine_test_env.outputs.name }}
