name: "Create test environment for each new PR"
on:
  pull_request:
    branches: ["next-minor"]
    types:
      - opened

permissions:
  actions: read
  contents: read
  packages: write

jobs:
  create_test_environment:
    runs-on: ubuntu-latest
    environment:
      name: pr-test-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/workflows/create_test_env.yml
        with:
          envName: "pr-${{ github.event.number }}"
        secrets: inherit