name: Determine test environment name and source SHA

on:
  workflow_call:
    inputs:
      envName:
        description: "Explicit environment name for manual runs"
        required: false
        type: string
    outputs:
      name:
        description: "Resolved test environment name"
        value: ${{ jobs.determine.outputs.name }}
      source_sha:
        description: "Resolved test environment commit SHA"
        value: ${{ jobs.determine.outputs.source_sha }}

jobs:
  determine:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.resolve.outputs.name }}
      source_sha: ${{ steps.resolve.outputs.source_sha }}
    steps:
      - id: resolve
        shell: bash
        run: |
          EVENT="${{ github.event_name }}"
          if [[ "$EVENT" == 'pull_request' ]]; then
            echo "name=pr${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
            echo "source_sha=$(echo '${{ github.event.pull_request.head.sha }}')" >> "$GITHUB_OUTPUT"
          elif [[ "$EVENT" == 'push' ]]; then
            # Turn / into - and make all lowercase
            safe_branch_name=$(echo "${{ github.ref_name }}" | sed 's/[\/+|<>,;_]/-/g' | tr '[:upper:]' '[:lower:]')
            echo "name=$safe_branch_name" >> "$GITHUB_OUTPUT"
            echo "source_sha=$(echo '${{ github.sha }}')" >> "$GITHUB_OUTPUT"
          else
            echo "Unsupported event ${EVENT}" >&2
            exit 1
          fi
