name: Frontend - Publish snapshot
permissions:
  contents: read
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend

jobs:
  build_and_test:
    uses: ./.github/workflows/frontend_build_test.yml
    outputs:
      project_version: ${{ steps.build_and_test.outputs.project_version }}
    secrets: inherit
  publish:
    needs: [build_and_test]
    uses: ./.github/workflows/frontend_publish_to_s3.yml
    with:
      publish_type: 'snapshot'
      project_version: ${{ needs.build_and_test.outputs.project_version }}
    secrets: inherit
