name: Frontend - Publish release

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      project_version:
        description: "Base semantic version (e.g. 13.6.0)"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      project_version:
        description: "Base semantic version (e.g. 13.6.0)"
        required: true

defaults:
  run:
    working-directory: frontend

env:
  PROJECT_VERSION: ${{ inputs.project_version || github.event.inputs.project_version }}

jobs:
  build_and_test_libs:
    uses: ./.github/workflows/frontend_build_test_libraries.yml
    with:
      project_version: ${{ github.env.PROJECT_VERSION }}
    secrets: inherit

  publish_libs:
    needs:
      - build_and_test_libs
    uses: ./.github/workflows/frontend_publish_to_npm.yml
    with:
      project_version: ${{ github.env.PROJECT_VERSION }}
      frontend_libraries_build_artifact_name: ${{ needs.build_and_test_libs.outputs.build_artifact_name }}
    secrets: inherit

  publish_image:
    needs:
      - build_and_test_libs
      - determine_version
    uses: ./.github/workflows/frontend_build_push_docker_image.yml
    with:
      frontend_libraries_build_artifact_name: ${{ needs.build_and_test_libs.outputs.build_artifact_name }}
      push_to_dockerhub: true
      release_image_tag: ${{ github.env.PROJECT_VERSION }}
