name: Frontend - Publish to NPMJS

on:
  workflow_call:
    inputs:
      project_version:
        description: "The determined project version. Required for release-candidate, not for snapshot"
        required: false
        type: string

defaults:
  run:
    working-directory: frontend

permissions:
  contents: read

jobs:
  build_and_test:
    uses: ./.github/workflows/frontend_build_test.yml
    secrets: inherit

  publish:
    runs-on: ubuntu-latest
    needs:
      - build_and_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: 'Restore build artifact: dist'
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: frontend/dist

      - name: 'Publish all libs to NPM'
        env:
          NPM_JS_REPOSITORY_AUTH_TOKEN: ${{ secrets.NPM_JS_REPOSITORY_AUTH_TOKEN }}
          PROJECT_VERSION: ${{ inputs.project_version }}
        run: |
          npm run libs-publish-all -- release $NPM_JS_REPOSITORY_AUTH_TOKEN $PROJECT_VERSION