name: Frontend - Publish release

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      project_version:
        description: 'Project version'
        required: true

defaults:
  run:
    working-directory: frontend

jobs:
  build_and_test:
    uses: ./.github/workflows/frontend_build_test.yml
    with:
      project_version: ${{ github.event.inputs.project_version }}
    secrets: inherit

  publish:
    if: ${{ startsWith(github.ref_name, 'release/') }}
    needs: build_and_test
    uses: ./.github/workflows/frontend_publish_to_npm.yml
    with:
      project_version: ${{ github.event.inputs.project_version }}
    secrets: inherit
