name: Frontend - Publish snapshot
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches: ['next-minor', 'feature/*']
    paths:
      - frontend/**
      - .github/workflows/frontend_publish_snapshot.yml

defaults:
  run:
    working-directory: frontend

jobs:
  build_and_test:
    uses: ./.github/workflows/frontend_build_test.yml
    secrets: inherit

  publish:
    needs: [build_and_test]
    uses: ./.github/workflows/frontend_publish_to_s3.yml
    with:
      publish_type: 'snapshot'
    secrets: inherit
