name: Tag test environment image
on:
  workflow_call:
    inputs:
      target:
        description: "Can be one of 'gzac-frontend', 'gzac-backend', (TODO:) 'valtimo-frontend' or 'valtimo-backend'"
        required: true
        type: string
      image_to_tag:
        description: "Existing image tag that will receive an additional tag for the test environment. E.g. next-minor.15"
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  determine_test_env:
    uses: ./.github/workflows/determine_test_env.yml

  tag_test_env:
    runs-on: ubuntu-latest
    needs:
      - determine_test_env
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Tag image for test environment
        env:
          IMAGE: "ghcr.io/valtimo-platform/${{ inputs.target }}"
          IMAGE_TO_TAG: ${{ inputs.image_to_tag }}
          TEST_ENV_TAG: "testEnv-${{ needs.determine_test_env.outputs.name }}-${{ needs.determine_test_env.outputs.source_sha}}-${{ github.run_number }}"
        run: |
          docker buildx imagetools create \
            --tag "${IMAGE}:${TEST_ENV_TAG}" \
            "${IMAGE_TO_TAG}"
