/*
 * Copyright 2015-2026 Ritense BV, the Netherlands.
 *
 * Licensed under EUPL, Version 1.2 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ritense.externalplugin.compatibility

import org.springframework.beans.factory.ObjectProvider
import org.springframework.boot.info.BuildProperties

/**
 * Resolves the running GZAC version from, in order of precedence:
 *
 * 1. The `valtimo.external-plugin.gzac-version` property — an explicit operator override, useful in
 *    tests or when the build metadata is unavailable or wrong.
 * 2. Spring's [BuildProperties] (`build.version`), generated by `springBoot { buildInfo() }`. This
 *    is the canonical source and is present both for `bootRun` and packaged artifacts.
 * 3. The implementation version on this class' jar manifest — a fallback for packaged artifacts
 *    that ship without build-info.
 *
 * Returns `null` when none of these resolve, in which case compatibility cannot be judged.
 */
class DefaultGzacVersionProvider(
    private val buildProperties: ObjectProvider<BuildProperties>,
    private val versionOverride: String?,
) : GzacVersionProvider {

    override fun getCurrentVersion(): String? {
        versionOverride?.takeIf { it.isNotBlank() }?.let { return it }
        buildProperties.ifAvailable?.version?.takeIf { it.isNotBlank() }?.let { return it }
        return javaClass.`package`?.implementationVersion?.takeIf { it.isNotBlank() }
    }
}
